spring:
  application:
    name: application
  http:
    multipart:
      maxFileSize: 10Mb
  host: 192.168.233.133
    port: 6379
    database: 0
    password: 123456
    pool:
      max-active: 4
      max-idle: 4
      min-idle: 0
      max-wait: 0
      timeout: 30
  datasource:
    url: jdbc:mysql://192.168.233.133:3306/bishe?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 5
      test-on-borrow: true
#  zipkin:
#    base-url: http://localhost:9411
  kafka:
     bootstrap-servers: 192.168.233.133:9092
     consumer:
       group-id: defaultGroup
       consumer:  
         key-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
       producer:
         key-serializer:  org.apache.kafka.common.serialization.StringDeserializer
         value-serializer:  org.apache.kafka.common.serialization.StringDeserializer
         batch-size: 65536
         buffer-memory: 524288
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    enabled: true
    content-type: text/html
    check-template: true
    cache: false
    check-template-location: true
    servlet:
      content-type: text/html;charset=utf-8
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.demo.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    # key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: com.example.demo.configure.MyMetaObjectHandler
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
server:
  port: 8156
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
