spring:
  application:
    name: application
#  zipkin:
#    base-url: http://localhost:9411
  kafka:
     bootstrap-servers: 192.168.233.129:9092
     consumer:
       group-id: defaultGroup
       consumer:  
         key-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
       producer:
         key-serializer:  org.apache.kafka.common.serialization.StringDeserializer
         value-serializer:  org.apache.kafka.common.serialization.StringDeserializer
         batch-size: 65536
         buffer-memory: 524288
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    enabled: true
    content-type: text/html; charset=utf-8
    check-template: true
    cache: false
    check-template-location: true
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
server:
  port: 8328
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
